name: Action Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install specific version of Google Chrome and latest ChromeDriver
        run: |
          sudo apt-get install -y wget unzip
          # Install a specific version of Google Chrome
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
          sudo dpkg -i google-chrome-stable_114.0.5735.90-1_amd64.deb || sudo apt-get -f install -y
          # Get the latest ChromeDriver version
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Set up DBus
        run: |
          sudo apt-get update
          sudo apt-get install -y dbus dbus-x11
          sudo service dbus start
          eval $(dbus-launch)
          echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> $GITHUB_ENV
          echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Get Python version
        run: python -V

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Save cookies
        run: python save_cookies.py

      - name: Run Python
        run: python python-sample.py
